version: '3.7'

networks:
  node-app:

services:
  db:
    image: postgres_node
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME_DEVELOPMENT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

    networks:
      - node-app
    ports:
      - 5433:5432
    restart: always

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    networks:
      - node-app
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
    ports:
      - "3000:3000"
    restart: always

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
      target: development
    networks:
      - node-app
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
    - .env
    restart: always
    command: npm run start:dev
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  docker-nest-postgres: