version: '3.7'

networks:
  node-app:

services:
  db:
    build: 
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME_DEVELOPMENT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}  
    ports:
      - 5432:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    networks:
      - node-app
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 80:80
    restart: always

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
    - .env
    # Run a command against the development stage of the image
    restart: always
    command: npm run start:dev
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  docker-nest-postgres: